on:
  push: 
    branches:
    - main

jobs:
  window_package_job:
    name: 打包linux可执行程序
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 安装dioxus-cli
      run: cargo install dioxus-cli
    
    - name: 打包运行.exe文件
      run: dx bundle --release
